<table>
  <tr>
    <th>Deployed Report</th>
  </tr>
  <tr>
    <td>
      <b>Generated By:</b> {{Auth::user()->name}}
    </td>
  </tr>
  <tr>
    <td>
      <b>Date:</b> {{Carbon\Carbon::now()->format('M d, Y')}}
    </td>
  </tr>
</table>

<table>
  <tr>
    <th>Deployed</th>
  </tr>
  <tr>
    <td>{{$deployed}} devices</td>
  </tr>
</table>

<table>
  <tr>
    <th>Serial</th>
    <th>Model</th>
    <th>Hardware Type</th>
    <th>Brand</th>
    <th>Employee ID</th>
    <th>Seat Number</th>
    <th>Owner</th>

    <th>Deployed Date</th>
    <th>Deployed By</th>
  </tr>
  @forelse($hardwares as $key=>$hardware)
  <tr>
    <td>{{$hardware->serial}}</td>
    <td>{{$hardware->model_name}}</td>
    <td>{{$hardware->hardware_type}}</td>
    <td>{{$hardware->brand}}</td>

    @foreach(App\Employee::where('hardware_id', $hardware->id)->orderBy('updated_at', 'desc')->cursor() as $key=>$employee)
    @if($key === 0 && $hardware->status !== 'Inventory')
    <td>{{ $employee->emp_id }}</td>
    <td>{{ $employee->seat }}</td>
    <td>{{ $employee->name }}</td>
    <td>{{ Carbon\Carbon::parse( $employee->hardware->deployed_date)->format('M d, Y') }}</td>
    @endif($hardware->status === 'Inventory')
    @endforeach
    <td>{{ $hardware->deployed_by->name }}</td>
  </tr>
  @empty
  @endforelse
</table>
